# Development Docker Compose Configuration
version: '3.8'

services:
  # MySQL Database for Development
  mysql:
    image: mysql:8.0
    container_name: mw_recommender_db_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-devpassword}
      MYSQL_DATABASE: ${DB_NAME:-mwonya_dev}
      MYSQL_USER: ${DB_USER:-dev_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dev_password}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - mw_recommender_dev_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis for Development
  redis:
    image: redis:7-alpine
    container_name: mw_recommender_redis_dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - mw_recommender_dev_network

  # Development API with hot reload
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mw_recommender_api_dev
    restart: unless-stopped
    ports:
      - "${API_PORT:-8001}:8000"
    environment:
      - DB_HOST=mysql
      - DB_USER=${DB_USER:-dev_user}
      - DB_PASSWORD=${DB_PASSWORD:-dev_password}
      - DB_NAME=${DB_NAME:-mwonya_dev}
      - DB_PORT=3306
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    networks:
      - mw_recommender_dev_network
    volumes:
      - ./api:/app/api:ro
      - ./run_api.py:/app/run_api.py:ro
      - ./logs:/app/logs

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  mw_recommender_dev_network:
    driver: bridge